fm_elfinder:
    assets_path: /assets # chemin des fichiers JS
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser
<<<<<<< HEAD
            # include_assets: true # Charge automatiquement les fichiers nécessaires
=======
>>>>>>> 1a15b9c39befc6b3acd191ed526c9da49bb6664b
            connector:
                debug: false # Désactive le débug
                roots:
                    uploads:
                        show_hidden: false # Masque les fichiers cachés
                        driver: LocalFileSystem # Pilote des fichiers
                        path: uploads # Chemin d'upload
<<<<<<< HEAD
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg'] # Fichiers autorisés
                        upload_deny: ['all'] # Fichiers interdits
                        upload_max_size: 2M # Taille maximum
=======
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'image/webp', 'video', 'pdf'] # Fichiers autorisés
                        upload_deny: ['all'] # Fichiers interdits
                        upload_max_size: 8M # Taille maximum

>>>>>>> 1a15b9c39befc6b3acd191ed526c9da49bb6664b
