twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    cache: false
=======
    globals:
        site_name: "Nom du site"
        version: "2.0"
        date_update: "05/08/2023"
        google_maps: ""
        recaptcha_public: ''
        recaptcha_private: ''
        mailjet_public: ''
        mailjet_private: ''
        posts_img_directory: '/uploads/images/posts'
>>>>>>> 1a15b9c39befc6b3acd191ed526c9da49bb6664b

when@test:
    twig:
        strict_variables: true
