<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => 'cc7a0154a53b81ea3424bac835064c89',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default',
  'DATABASE_URL' => 'mysql://root:root@127.0.0.1:3306/_air_creation?serverVersion=5.7&charset=utf8mb4',
  'MAILER_DSN' => 'smtp://hello@creative-eye.fr:Cre@tive_Eye_2022@smtp.ionos.fr:25',
);
