<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'cc7a0154a53b81ea3424bac835064c89',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default',
  'DATABASE_URL' => 'mysql://aircreation:GKVHhCy8VPqdm4@sb54548-007.eu.clouddb.ovh.net:35427/aircreation?serverVersion=5.7&charset=utf8mb4',
  'MAILER_DSN' => 'sendmail://default',
);
