version: '3.8'

services:
    db:
        image: mysql:5.7
        container_name: Database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
        ports:
            - "3308:3308"
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: PhpMyAdmin
        depends_on:
            - db
        environment:
            PMA_HOST: db
        restart: always
        ports:
            - 8090:80

    web:
        container_name: Website
        build: .
        depends_on:
            - db
        ports:
            - 8001:80
        environment:
            DATABASE_URL: mysql://db_user:db_user_pass@db:3306/main?serverVersion=5.7&charset=utf8mb4

volumes:
    dbdata: