# This is a basic workflow to help you get started with Actions

name: Deploy FTP

# Controls when the workflow will run
on:
  push:
    branches: 
      - 'prod'

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.japet.bsi.fr
        username: gkyqrkn-aircreation
        password: yK3hiVqJowjSge
        protocol: ftp
        exclude: |
          **/.git*
          **/.git*/**
          **/assets/**
          **/node_modules/**
          **/var/**
    
    - name: Databases migration
      run: bin/console make:migration
    
    - name: Databases update
      run: bin/console doctrine:migrations:migrate
